version: "3.3"
services:
  ui:
    build: .
    restart: always
    container_name: ui
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/srv/package/main
      - ../../apps:/srv/package/apps
    ports:
      - 80:80
      - 443:443
    command: [nginx-debug, '-g', 'daemon off;']
