const prefix = 'ToDoEvents';
export default {
  LIST_CREATED: `${prefix}.LIST_CREATED`,
  LIST_ITEM_CREATED: `${prefix}.LIST_ITEM_CREATED`,
  LIST_DELETED: `${prefix}.LIST_DELETED`,
  LIST_ITEM_DELETED: `${prefix}.LIST_ITEM_DELETED`,
  LIST_LOADED: `${prefix}.LIST_LOADED`,
  LIST_ITEMS_LOADED: `${prefix}.LIST_ITEMS_LOADED`,
  SELECTED_LIST_CHANGED: `${prefix}.SELECTED_LIST_CHANGED`,
  Errors: {
    LIST_ITEMS_LOAD_ERROR: `${prefix}.LIST_ITEMS_LOAD_ERROR`,
    LIST_LOAD_ERROR: `${prefix}.LIST_LOAD_ERROR`,
    LIST_CREATE_ERROR: `${prefix}.LIST_CREATE_ERROR`,
    LIST_ITEM_CREATE_ERROR: `${prefix}.LIST_ITEM_CREATE_ERROR`,
    LIST_DELETE_ERROR: `${prefix}.LIST_DELETE_ERROR`,
    LIST_ITEM_DELETE_ERROR: `${prefix}.LIST_ITEM_DELETE_ERROR`
  }
};
